--- #YAML:1.0
name:               HTML-Encoding
version:            0.61
abstract:           Determine the encoding of HTML/XML/XHTML documents
author:
    - Bjoern Hoehrmann <bjoern@hoehrmann.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               0
    HTML::Parser:         0
    HTTP::Headers::Util:  0
    HTTP::Response:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
