--- #YAML:1.0
name:                HTML-Encoding
version:             0.58
abstract:            Determine the encoding of HTML/XML/XHTML documents
license:             perl
author:              
    - Bjoern Hoehrmann <bjoern@hoehrmann.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Encode:                        0
    HTML::Parser:                  0
    HTTP::Headers::Util:           0
    HTTP::Response:                0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
